# Site settings
title: Alex Tomala
email: alex@atomala.com
description: >
  Welcome to my site, I do stuff with computers (and other things)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://atomala.com" # the base hostname & protocol for your site

#collections:
#  posts:
#    permalink: /blog/:title/
#    output: true

# Build settings
markdown: kramdown

sass:
  style: compressed

